#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Mar 15 13:52:25 2017

@author: brendontucker

taken from sentdx Regression Intro - Practical Machine Learning Tutorial with Python p.2
"""

import pandas as pd
import quandl, math
import numpy as np
from sklearn import preprocessing, cross_validation, svm
from sklearn.linear_model import LinearRegression

df = quandl.get('WIKI/GOOGL')


#prunning the data for the values needed
df = df[['Adj. Open', 'Adj. High', 'Adj. Low', 'Adj. Close', 'Adj. Volume']]

#transforming the data into more useful metrics

df['HL_PCT'] = (df['Adj. High'] - df['Adj. Close']) / df['Adj. Close'] * 100 
df['PCT_change'] = (df['Adj. Close'] - df['Adj. Open']) / df['Adj. Close'] * 100

df = df[['Adj. Close', 'HL_PCT', 'PCT_change', 'Adj. Volume']]

forecast_col = 'Adj. Close'
df.fillna(-99999, inplace=True)
forecast_out = int(math.ceil(.01*len(df)))#could add a few columns here to see
#if changing the forecasting windown/date affects the output that much


df['label'] = df[forecast_col].shift(-forecast_out)

#features 
X = np.array(df.drop(['label'], 1))


